name: show_new_dependencies

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: git checkout HEAD^
        run:
          git checkout HEAD^
      - name: ls
        run:
          ls -l
